=== liorerez7/SheetCell/out/SorceCode/Engine/src/CoreParts/impl/InnerSystemComponents/shtisel-v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="STL-Size">
		<xs:complexType>
			<xs:attribute name="rows-height-units" type="xs:int" use="required"/>
			<xs:attribute name="column-width-units" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="STL-Sheet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="STL-Layout"/>
				<xs:element ref="STL-Cells"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="STL-Original-Value" type="xs:string"/>
	<xs:element name="STL-Layout">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="STL-Size"/>
			</xs:sequence>
			<xs:attribute name="rows" type="xs:int" use="required"/>
			<xs:attribute name="columns" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="STL-Cells">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="STL-Cell" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="STL-Cell">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="STL-Original-Value"/>
			</xs:sequence>
			<xs:attribute name="row" type="xs:int" use="required"/>
			<xs:attribute name="column" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== liorerez7/SheetCell/out/SorceCode/Engine/src/CoreParts/impl/InnerSystemComponents/chatGptExample3.xml
<?xml version="1.0" encoding="UTF-8"?>
<STL-Sheet name="circular" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shtisel-v1.xsd">
	<STL-Layout rows="10" columns="3">
		<STL-Size column-width-units="12" rows-height-units="2"/>
	</STL-Layout>
	<STL-Cells>
		<STL-Cell row="1" column="A">
			<STL-Original-Value>{PLUS,{REF,B2}, 3}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="1" column="B">
			<STL-Original-Value>10</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="1" column="C">
			<STL-Original-Value>{PLUS,{REF,A1},{REF,B1}}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="2" column="A">
			<STL-Original-Value>{PLUS,{REF,B1},{REF,C1}}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="2" column="B">
			<STL-Original-Value>{PLUS,{REF,A2}, 5}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="2" column="C">
			<STL-Original-Value>{PLUS,{REF,A2},{REF,B2}}</STL-Original-Value>
		</STL-Cell>
	</STL-Cells>
</STL-Sheet>

=== liorerez7/SheetCell/Engine/src/Utility/STLSheetXmlExamples/insurance.xml
<?xml version="1.0" encoding="UTF-8"?>
<STL-Sheet name="Car Insurance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shtisel-v1.xsd">
	<STL-Layout rows="7" columns="7">
		<STL-Size column-width-units="10" rows-height-units="1"/>
	</STL-Layout>
	<STL-Cells>
		<STL-Cell row="4" column="B">
			<STL-Original-Value>AIG</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="5" column="B">
			<STL-Original-Value>WOBI</STL-Original-Value>
		</STL-Cell>		
		<STL-Cell row="6" column="B">
			<STL-Original-Value>SHIRBIT</STL-Original-Value>
		</STL-Cell>					
		<STL-Cell row="3" column="C">
			<STL-Original-Value>mandatory</STL-Original-Value>
		</STL-Cell>		
		<STL-Cell row="4" column="C">
			<STL-Original-Value>1000</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="5" column="C">
			<STL-Original-Value>900</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="6" column="C">
			<STL-Original-Value>5555</STL-Original-Value>
		</STL-Cell>						
		<STL-Cell row="3" column="D">
			<STL-Original-Value>3rd party</STL-Original-Value>
		</STL-Cell>		
		<STL-Cell row="4" column="D">
			<STL-Original-Value>800</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="5" column="D">
			<STL-Original-Value>1100</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="6" column="D">
			<STL-Original-Value>4444</STL-Original-Value>
		</STL-Cell>		
		<STL-Cell row="3" column="E">
			<STL-Original-Value>Total</STL-Original-Value>
		</STL-Cell>		
		<STL-Cell row="4" column="E">
			<STL-Original-Value>{PLUS,{REF,C4},{REF,D4}}</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="5" column="E">
			<STL-Original-Value>{PLUS,{REF,C5},{REF,D5}}</STL-Original-Value>
		</STL-Cell>		
				<STL-Cell row="6" column="E">
			<STL-Original-Value>{PLUS,{REF,C6},{REF,D6}}</STL-Original-Value>
		</STL-Cell>								
	</STL-Cells>
</STL-Sheet>

=== liorerez7/SheetCell/out/SorceCode/Engine/src/CoreParts/impl/InnerSystemComponents/chatGptExample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<STL-Sheet name="intermediate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shtisel-v1.xsd">
	<STL-Layout rows="20" columns="5">
		<STL-Size column-width-units="4" rows-height-units="1"/>
	</STL-Layout>
	<STL-Cells>
		<STL-Cell row="3" column="A">
			<STL-Original-Value>3.14</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="3" column="B">
			<STL-Original-Value>2</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="3" column="C">
			<STL-Original-Value>{TIMES,{REF,A3},{REF,B3}}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="4" column="A">
			<STL-Original-Value>{PLUS,{REF,C3},4}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="4" column="B">
			<STL-Original-Value>{CONCAT,Hello, World}</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="4" column="C">
			<STL-Original-Value>{SUB,HelloWorld,4,7}</STL-Original-Value>
		</STL-Cell>
	</STL-Cells>
</STL-Sheet>

=== liorerez7/SheetCell/Engine/src/CoreParts/impl/basic.xml
<?xml version="1.0" encoding="UTF-8"?>
<STL-Sheet name="beginner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shtisel-v1.xsd">
	<STL-Layout rows="3" columns="5">
		<STL-Size column-width-units="15" rows-height-units="3"/>
	</STL-Layout>
	<STL-Cells>
		<STL-Cell row="2" column="B">
			<STL-Original-Value>Hello</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="2" column="C">
			<STL-Original-Value>Menash</STL-Original-Value>
		</STL-Cell>
		<STL-Cell row="2" column="D">
			<STL-Original-Value>{CONCAT,{REF,B2},{REF,C2}}</STL-Original-Value>
		</STL-Cell>
	</STL-Cells>
</STL-Sheet>
